# -*- coding: utf-8 -*-
"""mltak1_merged_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ey8dDo7MVtzbLwEUS7TVr2PiCChaRHHI
"""

# Google Colab / local file input
# This cell uploads mltak1Data.xlsx into the current Colab runtime.

import os

FILE_NAME = "mltak1Data.xlsx"

try:
    from google.colab import files
    print("Please upload:", FILE_NAME)
    uploaded = files.upload()

    if FILE_NAME in uploaded:
        print(f"Uploaded successfully: {FILE_NAME}")
    elif uploaded:
        # Keep compatibility if the uploaded file has a different visible name.
        uploaded_name = next(iter(uploaded))
        print(f"Uploaded file detected: {uploaded_name}")
        FILE_NAME = uploaded_name
    else:
        raise FileNotFoundError("No file was uploaded.")
except ImportError:
    # Local/Jupyter fallback
    if not os.path.exists(FILE_NAME):
        raise FileNotFoundError(
            f"'{FILE_NAME}' was not found. Put the Excel file in the notebook working directory."
        )

print("Using Excel file:", FILE_NAME)

# Install the Excel reader if needed in Colab
!pip -q install openpyxl

"""## Program 1"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix as pdf
import seaborn as sns

data = pd.read_excel(FILE_NAME,usecols=['search','tak3','tak2','tak1','final','midterm'])

#search=list(data['search'])
#tak3=list(data['tak3'])
#tak2=list(data['tak2'])
#tak1=list(data['tak1'])
#final=list(data['final'])
#midterm=list(data['midterm'])


pff = pd.plotting.scatter_matrix(data.iloc[:, 0:7])
plt.show()
fig, ax = plt.subplots(figsize=(10,6))
sns.heatmap(data.corr(), center=0, cmap='Greens')

plt.show()
np.linspace

"""## Program 2"""

import math
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pandas.plotting import scatter_matrix as pdf

# Creating a series of data of in range of 1-50.

data = pd.read_excel( FILE_NAME, 0 )
datas = data.sort_values( 'total' )




def gaussian_transform(datas):

    u=data["total"].mean()

    sig=data['total'].std()

    fd=[]

    a=0
    pi=math.pi
    for i in datas:

        a=((i-u)**2)/(2*(sig**2))
        e=math.exp(-a)
        fd.append((1/(sig*math.sqrt(2*pi))) * e)


    return fd


y=gaussian_transform(datas["total"])

plt.plot(datas["total"],y)
plt.xlim(6.8,18.8)
plt.show()